fos_ck_editor:
  default_config: praguebest_sylius_footer_plugin
  configs:
    praguebest_sylius_footer_plugin:
      toolbar: praguebest_sylius_footer_plugin
      enterMode: 3
      forcePasteAsPlainText: 'allow-word'
      allowedContent: true
      extraPlugins:
        - 'mediaVideo'
        - 'mediaImage'
  plugins:
    mediaVideo:
      path: '/bundles/praguebestsyliusfooterplugin/js/ckeditor-plugins/video/'
      filename: 'plugin.js'
    mediaImage:
      path: '/bundles/praguebestsyliusfooterplugin/js/ckeditor-plugins/image/'
      filename: 'plugin.js'
  toolbars:
    configs:
      praguebest_sylius_footer_plugin:
        - '@standard.clipboard'
        - '@standard.editing'
        - '@standard.links'
        - '@standard.insert'
        - '@standard.tools'
        - '@standard.document'
        - '/'
        - '@standard.basic_styles'
        - '@standard.paragraph'
        - '@standard.about'
    items:
      standard.insert: ['Image', 'MediaVideo', 'MediaImage', 'Table', 'HorizontalRule', 'SpecialChar']
