imports:
  - { resource: "@PraguebestSyliusFooterPlugin/Resources/config/resources.yml" }
  - { resource: "@PraguebestSyliusFooterPlugin/Resources/config/ckeditor/ckeditor.yml" }
  - { resource: "@PraguebestSyliusFooterPlugin/Resources/config/grids.yml" }
  - { resource: "@PraguebestSyliusFooterPlugin/Resources/config/services.yml" }
  - { resource: "@PraguebestSyliusFooterPlugin/Resources/config/media_provider.yml" }
  - { resource: "@PraguebestSyliusFooterPlugin/Resources/config/forms.yml" }
  - { resource: "@PraguebestSyliusFooterPlugin/Resources/config/controller.yml" }

parameters:
  praguebest_validation_group: [praguebest_footer]
  praguebest_sylius_footer_plugin.form.type.footer.validation_groups: "%praguebest_validation_group%"
  praguebest_sylius_footer_plugin.form.type.translation.footer.validation_groups: "%praguebest_validation_group%"

jms_serializer:
  metadata:
    directories:
      praguebest-section:
        namespace_prefix: "Praguebest\\SyliusFooterPlugin"
        path: "@PraguebestSyliusFooterPlugin/Resources/config/serializer"