Praguebest\SyliusFooterPlugin\Entity\FooterTranslation:
  type: entity
  table: sylius_footer_translation
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    locale:
      column: locale
      type: string
      length: 10
      nullable: true
    name:
      column: name
      type: string
      nullable: true
    copyright:
      column: copyright
      type: string
      nullable: true