Praguebest\SyliusFooterPlugin\Entity\Footer:
  type: entity
  table: sylius_footer
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    isDefault:
      column: is_default
      type: boolean
    hasSocials:
      column: has_socials
      type: boolean
    hasNewsletter:
      column: has_newsletter
      type: boolean
    hasCopyright:
      column: has_copyright
      type: boolean
    enabled:
      column: enabled
      type: boolean
    createdAt:
      column: created_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      column: updated_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update

  manyToMany:
    taxons:
      targetEntity: Sylius\Component\Core\Model\TaxonInterface
      joinTable:
        name: sylius_footer_taxon
        joinColumns:
          footer_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          taxon_id:
            referencedColumnName: id
            onDelete: CASCADE
    footerBlocks:
      targetEntity: Praguebest\SyliusFooterPlugin\Entity\FooterBlockInterface
      joinTable:
        name: sylius_footer_footer_block
        joinColumns:
          footer_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          footer_block_id:
            referencedColumnName: id
            onDelete: CASCADE
