Praguebest\SyliusFooterPlugin\Entity\FooterBlock:
  type: entity
  table: sylius_footer_block
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    enabled:
      column: enabled
      type: boolean
    createdAt:
      column: created_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      column: updated_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update